### ISSUE TITLE
1.0.1 - node.js complains about window.URL

### ISSUE THREAD

**Issue by snypelife** [substack/webworkify#6]
Upgrading to the latest `1.0.1` causes the following issue when trying to run.

This is how it's being used, so pretty basic.

```
var Work = require('webworkify');
var ImageWorker = require('../workers/process-image');
.
.
.
var imageWorker = Work(ImageWorker);
```

Here's the stack output:

```
/Users/snypelife/project/node_modules/webworkify/index.js:6
var URL = window.URL || window.webkitURL || window.mozURL || window.msURL;
          ^
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/snypelife/project/node_modules/webworkify/index.js:6:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/snypelife/project/app/shared/partials/invoice.jsx:19:12)
    at Module._compile (module.js:456:26)
    at Object.require.extensions.(anonymous function) [as .jsx] (/Users/snypelife/project/node_modules/node-jsx/index.js:26:12)
```

**Comment by snypelife** [comment]
Looks like you might wanna bring that window.URL back into the module.exports.

**Comment by asvsfs** [comment]
There is no window on client side, you need to change your design .

**Comment by snypelife** [comment]
But if you have the same code running on both server and client?

**Comment by asvsfs** [comment]
Doesn't matter , you get this error from the part that is running on server

**Comment by snypelife** [comment]
Patch merged, closing issue.
